### ISSUE TITLE
call should work on normal functions, not just promises and generators

### ISSUE THREAD

**Issue by funkjunky** [wzrdzl/redux-yield-effect#1]
For anyone used to Sagas, who wants a more light weight solution, not having a call for normal functions is annoying. I made an effect that solves my problem, but I either have to call my description something else, or have two "call" effects.

On a side note, im glad you made this, it saved me the trouble. It's exactly what I was hoping to make, before my google searching revealed it was already made and almost exactly the way I wanted to make it :D

[also random FYI I'm working on turning redux and this, into an entity engine for games.]

**Comment by wzrdzl** [comment]
Hi @funkjunky ! Your proposal makes sense to me, would you open a PR for it?

**Comment by funkjunky** [comment]
Ya sure. I probably won't get around to it for a week or so. Sorta playing around with this on my free time.

**Comment by funkjunky** [comment]
So I very quickly glanced at the source code last time and didn't notice that the only thing stopping the effect from calling normal functions was an invariant.

Everything would still work the same, including your examples, because the examples pass a promise to call anyways.

Here is the pull request, I just removed a couple lines:
https://github.com/wzrdzl/redux-yield-effect/pull/2
