### ISSUE TITLE
Put doesn't return result from action

### ISSUE THREAD

**Issue by funkjunky** [wzrdzl/redux-yield-effect#4]
Like react-redux, it should return what the middleware returns.

In my case that could be a selector.

I patched it with: https://github.com/wzrdzl/redux-yield-effect/pull/3

**Comment by vovacodes** [comment]
Fixed by https://github.com/wzrdzl/redux-yield-effect/commit/eacf6dd4724cf96e28161ba3e30ad5c6f73955a6
